### ISSUE TITLE
SMTP Sending Mail fails when not using authentication

### ISSUE THREAD

**Issue by neandrake** [ONLYOFFICE/ONLYOFFICE-Server#6]
I'm testing the latest OnlyOffice service on a CentOS 7 setup. On my internal network my mail server allows for any internal IP to send email without providing credentials. When I configure OnlyOffice to use my internal SMTP server without credentials, the test email button will properly send an email, but when I click to send activation email, an exception will occur on OnlyOffice:

Contents of /var/log/onlyoffice/8.1/Notify.01-20.log
```
015-01-20 15:51:30,811 ERROR [NotifyThread 2015-01-20T20:51:30.7528260Z] ASC.Notify - Tenant: 0, To: person@company.com - System.Net.Mail.SmtpException: 535 5.7.8 Error: authentication failed: generic failure
  at System.Net.Mail.SmtpClient.CheckStatus (SmtpResponse status, Int32 i) [0x00000] in <filename unknown>:0 
  at System.Net.Mail.SmtpClient.Authenticate (System.String user, System.String password) [0x00000] in <filename unknown>:0 
  at System.Net.Mail.SmtpClient.Authenticate () [0x00000] in <filename unknown>:0 
  at System.Net.Mail.SmtpClient.SendCore (System.Net.Mail.MailMessage message) [0x00000] in <filename unknown>:0 
  at System.Net.Mail.SmtpClient.SendInternal (System.Net.Mail.MailMessage message) [0x00000] in <filename unknown>:0 
  at System.Net.Mail.SmtpClient.Send (System.Net.Mail.MailMessage message) [0x00000] in <filename unknown>:0 
```

When I supply credentials for the SMTP configuration on OnlyOffice, email will send again for activations.

A guess:
https://github.com/ONLYOFFICE/ONLYOFFICE-Server/blob/master/common/ASC.Core.Common/Notify/Senders/SmtpSender.cs#L210-L214
Is it possible that the credentials field here is not null but contains empty values? If so this check might need updated to account for such.

**Comment by neandrake** [comment]
Rather, this check here should probably not check for userName in the "properties", but should check the corresponding property for the "Authentication" checkbox on that form.
https://github.com/ONLYOFFICE/ONLYOFFICE-Server/blob/master/common/ASC.Core.Common/Notify/Senders/SmtpSender.cs#L82-L88

**Comment by AnaMih** [comment]
If you have some issues ocсuring in Onlyoffice configuration, we would like to offer you an official Docker container of OnlyOffice, which is already configured.
https://registry.hub.docker.com/u/ascensiosystemsia/onlyoffice-commonserver/

**Comment by neandrake** [comment]
Thank you for the link, but I'm not familiar with Docker. I don't see how this would fix my issue as it's dependent on my local mail server configuration. My mail server allows anything from the internal network to send without providing credentials, which is how I would like to have OnlyOffice configured to use the SMTP server.
